package com.demo.entities;
// Generated Dec 29, 2024, 4:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Douutien generated by hbm2java
 */
@Entity
@Table(name = "douutien")
public class Douutien implements java.io.Serializable {

	private int maDoUuTien;
	private String tenDoUuTien;
	private Set<Yeucau> yeucaus = new HashSet<Yeucau>(0);

	public Douutien() {
	}

	public Douutien(int maDoUuTien, String tenDoUuTien) {
		this.maDoUuTien = maDoUuTien;
		this.tenDoUuTien = tenDoUuTien;
	}

	public Douutien(int maDoUuTien, String tenDoUuTien, Set<Yeucau> yeucaus) {
		this.maDoUuTien = maDoUuTien;
		this.tenDoUuTien = tenDoUuTien;
		this.yeucaus = yeucaus;
	}

	@Id

	@Column(name = "MaDoUuTien", unique = true, nullable = false)
	public int getMaDoUuTien() {
		return this.maDoUuTien;
	}

	public void setMaDoUuTien(int maDoUuTien) {
		this.maDoUuTien = maDoUuTien;
	}

	@Column(name = "TenDoUuTien", nullable = false, length = 50)
	public String getTenDoUuTien() {
		return this.tenDoUuTien;
	}

	public void setTenDoUuTien(String tenDoUuTien) {
		this.tenDoUuTien = tenDoUuTien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "douutien")
	public Set<Yeucau> getYeucaus() {
		return this.yeucaus;
	}

	public void setYeucaus(Set<Yeucau> yeucaus) {
		this.yeucaus = yeucaus;
	}

}
