package com.demo.entities;
// Generated Dec 29, 2024, 4:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien")
public class Nhanvien implements java.io.Serializable {

	private String username;
	private String password;
	private String hoTen;
	private Date ngaySinh;
	private boolean kichHoat;
	private String hinhAnh;
	private int quyen;
	private Set<Yeucau> yeucausForMaNvGui = new HashSet<Yeucau>(0);
	private Set<Yeucau> yeucausForMaNvXuLy = new HashSet<Yeucau>(0);

	public Nhanvien() {
	}

	public Nhanvien(String username, String password, boolean kichHoat, int quyen) {
		this.username = username;
		this.password = password;
		this.kichHoat = kichHoat;
		this.quyen = quyen;
	}

	public Nhanvien(String username, String password, String hoTen, Date ngaySinh, boolean kichHoat, String hinhAnh,
			int quyen, Set<Yeucau> yeucausForMaNvGui, Set<Yeucau> yeucausForMaNvXuLy) {
		this.username = username;
		this.password = password;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.kichHoat = kichHoat;
		this.hinhAnh = hinhAnh;
		this.quyen = quyen;
		this.yeucausForMaNvGui = yeucausForMaNvGui;
		this.yeucausForMaNvXuLy = yeucausForMaNvXuLy;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "HoTen", length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "KichHoat", nullable = false)
	public boolean isKichHoat() {
		return this.kichHoat;
	}

	public void setKichHoat(boolean kichHoat) {
		this.kichHoat = kichHoat;
	}

	@Column(name = "HinhAnh")
	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@Column(name = "Quyen", nullable = false)
	public int getQuyen() {
		return this.quyen;
	}

	public void setQuyen(int quyen) {
		this.quyen = quyen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByMaNvGui")
	public Set<Yeucau> getYeucausForMaNvGui() {
		return this.yeucausForMaNvGui;
	}

	public void setYeucausForMaNvGui(Set<Yeucau> yeucausForMaNvGui) {
		this.yeucausForMaNvGui = yeucausForMaNvGui;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByMaNvXuLy")
	public Set<Yeucau> getYeucausForMaNvXuLy() {
		return this.yeucausForMaNvXuLy;
	}

	public void setYeucausForMaNvXuLy(Set<Yeucau> yeucausForMaNvXuLy) {
		this.yeucausForMaNvXuLy = yeucausForMaNvXuLy;
	}

}
