package com.demo.entities;
// Generated Dec 29, 2024, 4:08:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Yeucau generated by hbm2java
 */
@Entity
@Table(name = "yeucau")
public class Yeucau implements java.io.Serializable {

	private int maYeuCau;
	private Douutien douutien;
	private Nhanvien nhanvienByMaNvGui;
	private Nhanvien nhanvienByMaNvXuLy;
	private String tieuDe;
	private String noiDung;
	private Date ngayGui;

	public Yeucau() {
	}

	public Yeucau(int maYeuCau, Douutien douutien, Nhanvien nhanvienByMaNvGui, String tieuDe, String noiDung,
			Date ngayGui) {
		this.maYeuCau = maYeuCau;
		this.douutien = douutien;
		this.nhanvienByMaNvGui = nhanvienByMaNvGui;
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.ngayGui = ngayGui;
	}

	public Yeucau(int maYeuCau, Douutien douutien, Nhanvien nhanvienByMaNvGui, Nhanvien nhanvienByMaNvXuLy,
			String tieuDe, String noiDung, Date ngayGui) {
		this.maYeuCau = maYeuCau;
		this.douutien = douutien;
		this.nhanvienByMaNvGui = nhanvienByMaNvGui;
		this.nhanvienByMaNvXuLy = nhanvienByMaNvXuLy;
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.ngayGui = ngayGui;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaYeuCau", unique = true, nullable = false)
	public int getMaYeuCau() {
		return this.maYeuCau;
	}

	public void setMaYeuCau(int maYeuCau) {
		this.maYeuCau = maYeuCau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDoUuTien", nullable = false)
	public Douutien getDouutien() {
		return this.douutien;
	}

	public void setDouutien(Douutien douutien) {
		this.douutien = douutien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNvGui", nullable = false)
	public Nhanvien getNhanvienByMaNvGui() {
		return this.nhanvienByMaNvGui;
	}

	public void setNhanvienByMaNvGui(Nhanvien nhanvienByMaNvGui) {
		this.nhanvienByMaNvGui = nhanvienByMaNvGui;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNvXuLy")
	public Nhanvien getNhanvienByMaNvXuLy() {
		return this.nhanvienByMaNvXuLy;
	}

	public void setNhanvienByMaNvXuLy(Nhanvien nhanvienByMaNvXuLy) {
		this.nhanvienByMaNvXuLy = nhanvienByMaNvXuLy;
	}

	@Column(name = "TieuDe", nullable = false)
	public String getTieuDe() {
		return this.tieuDe;
	}

	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}

	@Column(name = "NoiDung", nullable = false)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayGui", nullable = false, length = 10)
	public Date getNgayGui() {
		return this.ngayGui;
	}

	public void setNgayGui(Date ngayGui) {
		this.ngayGui = ngayGui;
	}

}
